In [1]:
import pandas as pd
recomendados = pd.read_csv('validation/recomendando.csv')

df_movies = pd.read_csv('data/cbf_df.csv')
df_movies = df_movies.drop(columns=['geral', 'tag'])


df_testing = pd.read_csv('validation/testing.csv')


df_traning = pd.read_csv('validation/training.csv')



recomendados = recomendados.merge(df_movies, 'left', on='movieId').drop(columns=['titulo_movie_lens_y', 'genres2'])
recomendados = recomendados.rename(columns={'titulo_movie_lens_x': 'titulo_movie_lens'})


df_testing = df_testing.merge(df_movies, 'left', on='movieId').drop(columns=['genres2'])
df_traning = df_traning.merge(df_movies, 'left', on='movieId').drop(columns=['genres2'])

recomendados
df_testing
df_traning

,userId,movieId,rating,timestamp,titulo_movie_lens,genres
0,580,16,4.5,1167790725,Casino (1995),Crime|Drama
1,580,22,4.0,1167861702,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller
2,580,25,4.0,1167789966,Leaving Las Vegas (1995),Drama|Romance
3,580,32,5.0,1167790855,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
4,580,50,5.0,1167789884,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...
172,580,51662,5.0,1212342492,300 (2007),Action|Fantasy|War|IMAX
173,580,51935,5.0,1212342499,Shooter (2007),Action|Drama|Thriller
174,580,53972,4.5,1212342527,Live Free or Die Hard (2007),Action|Adventure|Crime|Thriller
175,580,53996,5.0,1212342502,Transformers (2007),Action|Sci-Fi|Thriller|IMAX
176,580,56174,4.5,1212342537,I Am Legend (2007),Action|Horror|Sci-Fi|Thriller|IMAX

In [2]:
dummies = recomendados['genres'].str.get_dummies(sep='|')
recomendados = pd.concat([recomendados, dummies], axis=1)
recomendados


dummies = df_testing['genres'].str.get_dummies(sep='|')
df_testing = pd.concat([df_testing, dummies], axis=1)
df_testing

dummies = df_traning['genres'].str.get_dummies(sep='|')
df_traning = pd.concat([df_traning, dummies], axis=1)
df_traning

,userId,movieId,rating,timestamp,titulo_movie_lens,genres,Action,Adventure,Animation,Children,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,580,16,4.5,1167790725,Casino (1995),Crime|Drama,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,580,22,4.0,1167861702,Copycat (1995),Crime|Drama|Horror|Mystery|Thriller,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
2,580,25,4.0,1167789966,Leaving Las Vegas (1995),Drama|Romance,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,580,32,5.0,1167790855,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller,0,0,0,0,...,0,0,0,0,1,0,1,1,0,0
4,580,50,5.0,1167789884,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,580,51662,5.0,1212342492,300 (2007),Action|Fantasy|War|IMAX,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
173,580,51935,5.0,1212342499,Shooter (2007),Action|Drama|Thriller,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
174,580,53972,4.5,1212342527,Live Free or Die Hard (2007),Action|Adventure|Crime|Thriller,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
175,580,53996,5.0,1212342502,Transformers (2007),Action|Sci-Fi|Thriller|IMAX,1,0,0,0,...,0,0,1,0,0,0,1,1,0,0
176,580,56174,4.5,1212342537,I Am Legend (2007),Action|Horror|Sci-Fi|Thriller|IMAX,1,0,0,0,...,0,1,1,0,0,0,1,1,0,0

In [7]:
recomendados_generos = recomendados.iloc[:, 4:]
recomendados_generos

df_traning_generos = df_traning.iloc[:, 6:]
df_traning_generos

df_testing_generos = df_testing.iloc[:, 6:]
df_testing_generos


recomendados_generos.sum().sort_values().to_csv('validation/resultado/soma_recomendados.csv')
df_traning_generos.sum().sort_values().to_csv('validation/resultado/soma_treino.csv')

df_testing_generos.sum().sort_values().to_csv('validation/resultado/soma_test.csv')